export const MATCH_CAPTURE_MODES = Object.freeze({
  LIVE: "live",
  MANUAL: "manual",
  ADMIN: "admin"
});

export const MATCH_WORKFLOW_STATUSES = Object.freeze({
  SCHEDULED: "scheduled",
  PENDING_LINEUPS: "pending_lineups",
  LINEUPS_PARTIAL: "lineups_partial",
  LINEUPS_COMPLETE: "lineups_complete",
  READY_TO_START: "ready_to_start",
  IN_PROGRESS: "in_progress",
  TEMPORARILY_SAVED: "temporarily_saved",
  SUSPENDED_PENDING_RESUME: "suspended_pending_resume",
  SUSPENDED_FINAL: "suspended_final",
  RESCHEDULED: "rescheduled",
  MATCH_FINISHED: "match_finished",
  PENDING_CAPTAIN_REVIEW: "pending_captain_review",
  CORRECTION_REQUESTED: "correction_requested",
  LOCAL_SIGNED: "local_signed",
  VISITOR_SIGNED: "visitor_signed",
  BOTH_SIGNED: "both_signed",
  READY_TO_FINALIZE: "ready_to_finalize",
  FINALIZING: "finalizing",
  FINALIZED_PENDING_SYNC: "finalized_pending_sync",
  FINALIZED: "finalized",
  PUBLISHED: "published",
  SYNC_ERROR: "sync_error"
});

export const MATCH_REPORT_STATUSES = Object.freeze({
  DRAFT: "draft",
  PRELIMINARY: "preliminary",
  PENDING_CAPTAIN_REVIEW: "pending_captain_review",
  CORRECTION_REQUESTED: "correction_requested",
  BOTH_SIGNED: "both_signed",
  FINALIZED: "finalized",
  PUBLISHED: "published"
});

export const MATCH_SIGNATURE_STATUSES = Object.freeze({
  PENDING: "pending",
  SIGNED: "signed",
  INVALIDATED: "invalidated",
  REJECTED: "rejected"
});

const PUBLICATION_STATUSES = new Set([
  MATCH_WORKFLOW_STATUSES.FINALIZED,
  MATCH_WORKFLOW_STATUSES.PUBLISHED
]);

const SIGNATURE_REQUIRED_MODES = new Set([
  MATCH_CAPTURE_MODES.LIVE
]);

const VALID_TRANSITIONS = Object.freeze({
  [MATCH_WORKFLOW_STATUSES.SCHEDULED]: [
    MATCH_WORKFLOW_STATUSES.PENDING_LINEUPS,
    MATCH_WORKFLOW_STATUSES.LINEUPS_PARTIAL,
    MATCH_WORKFLOW_STATUSES.LINEUPS_COMPLETE,
    MATCH_WORKFLOW_STATUSES.READY_TO_START,
    MATCH_WORKFLOW_STATUSES.IN_PROGRESS,
    MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW,
    MATCH_WORKFLOW_STATUSES.FINALIZED,
    MATCH_WORKFLOW_STATUSES.PUBLISHED
  ],
  [MATCH_WORKFLOW_STATUSES.PENDING_LINEUPS]: [
    MATCH_WORKFLOW_STATUSES.LINEUPS_PARTIAL,
    MATCH_WORKFLOW_STATUSES.LINEUPS_COMPLETE
  ],
  [MATCH_WORKFLOW_STATUSES.LINEUPS_PARTIAL]: [
    MATCH_WORKFLOW_STATUSES.LINEUPS_COMPLETE
  ],
  [MATCH_WORKFLOW_STATUSES.LINEUPS_COMPLETE]: [
    MATCH_WORKFLOW_STATUSES.READY_TO_START
  ],
  [MATCH_WORKFLOW_STATUSES.READY_TO_START]: [
    MATCH_WORKFLOW_STATUSES.IN_PROGRESS
  ],
  [MATCH_WORKFLOW_STATUSES.IN_PROGRESS]: [
    MATCH_WORKFLOW_STATUSES.TEMPORARILY_SAVED,
    MATCH_WORKFLOW_STATUSES.SUSPENDED_PENDING_RESUME,
    MATCH_WORKFLOW_STATUSES.SUSPENDED_FINAL,
    MATCH_WORKFLOW_STATUSES.MATCH_FINISHED,
    MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW,
    MATCH_WORKFLOW_STATUSES.FINALIZED
  ],
  [MATCH_WORKFLOW_STATUSES.TEMPORARILY_SAVED]: [
    MATCH_WORKFLOW_STATUSES.IN_PROGRESS,
    MATCH_WORKFLOW_STATUSES.SUSPENDED_PENDING_RESUME,
    MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW
  ],
  [MATCH_WORKFLOW_STATUSES.SUSPENDED_PENDING_RESUME]: [
    MATCH_WORKFLOW_STATUSES.IN_PROGRESS,
    MATCH_WORKFLOW_STATUSES.RESCHEDULED,
    MATCH_WORKFLOW_STATUSES.SUSPENDED_FINAL
  ],
  [MATCH_WORKFLOW_STATUSES.MATCH_FINISHED]: [
    MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW,
    MATCH_WORKFLOW_STATUSES.FINALIZED
  ],
  [MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW]: [
    MATCH_WORKFLOW_STATUSES.LOCAL_SIGNED,
    MATCH_WORKFLOW_STATUSES.VISITOR_SIGNED,
    MATCH_WORKFLOW_STATUSES.BOTH_SIGNED,
    MATCH_WORKFLOW_STATUSES.CORRECTION_REQUESTED
  ],
  [MATCH_WORKFLOW_STATUSES.LOCAL_SIGNED]: [
    MATCH_WORKFLOW_STATUSES.BOTH_SIGNED,
    MATCH_WORKFLOW_STATUSES.CORRECTION_REQUESTED
  ],
  [MATCH_WORKFLOW_STATUSES.VISITOR_SIGNED]: [
    MATCH_WORKFLOW_STATUSES.BOTH_SIGNED,
    MATCH_WORKFLOW_STATUSES.CORRECTION_REQUESTED
  ],
  [MATCH_WORKFLOW_STATUSES.CORRECTION_REQUESTED]: [
    MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW
  ],
  [MATCH_WORKFLOW_STATUSES.BOTH_SIGNED]: [
    MATCH_WORKFLOW_STATUSES.READY_TO_FINALIZE
  ],
  [MATCH_WORKFLOW_STATUSES.READY_TO_FINALIZE]: [
    MATCH_WORKFLOW_STATUSES.FINALIZING
  ],
  [MATCH_WORKFLOW_STATUSES.FINALIZING]: [
    MATCH_WORKFLOW_STATUSES.FINALIZED_PENDING_SYNC,
    MATCH_WORKFLOW_STATUSES.FINALIZED,
    MATCH_WORKFLOW_STATUSES.SYNC_ERROR
  ],
  [MATCH_WORKFLOW_STATUSES.FINALIZED_PENDING_SYNC]: [
    MATCH_WORKFLOW_STATUSES.FINALIZED,
    MATCH_WORKFLOW_STATUSES.SYNC_ERROR
  ],
  [MATCH_WORKFLOW_STATUSES.FINALIZED]: [
    MATCH_WORKFLOW_STATUSES.PUBLISHED
  ],
  [MATCH_WORKFLOW_STATUSES.SYNC_ERROR]: [
    MATCH_WORKFLOW_STATUSES.FINALIZED_PENDING_SYNC,
    MATCH_WORKFLOW_STATUSES.FINALIZED
  ]
});

export function normalizeCaptureMode(value) {
  return Object.values(MATCH_CAPTURE_MODES).includes(value) ? value : MATCH_CAPTURE_MODES.ADMIN;
}

export function normalizeWorkflowStatus(value, fallback = MATCH_WORKFLOW_STATUSES.SCHEDULED) {
  return Object.values(MATCH_WORKFLOW_STATUSES).includes(value) ? value : fallback;
}

export function requiresCaptainSignatures(captureMode) {
  return SIGNATURE_REQUIRED_MODES.has(normalizeCaptureMode(captureMode));
}

export function canPublishWithoutCaptainSignatures(captureMode) {
  return !requiresCaptainSignatures(captureMode);
}

export function isOfficialWorkflowStatus(status) {
  return PUBLICATION_STATUSES.has(normalizeWorkflowStatus(status));
}

export function canTransitionMatchWorkflow(fromStatus, toStatus) {
  const from = normalizeWorkflowStatus(fromStatus);
  const to = normalizeWorkflowStatus(toStatus);
  if (from === to) return true;
  return (VALID_TRANSITIONS[from] || []).includes(to);
}

export function getNextWorkflowStatusAfterFinish(captureMode) {
  return requiresCaptainSignatures(captureMode)
    ? MATCH_WORKFLOW_STATUSES.PENDING_CAPTAIN_REVIEW
    : MATCH_WORKFLOW_STATUSES.FINALIZED;
}
