-- Esquema Postgres/Supabase para Liga Municipal Futbol.
-- Ejecutar en Supabase SQL Editor para preparar la base del piloto.

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS leagues (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  season TEXT NOT NULL,
  current_competition_id TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  plan TEXT,
  owner_email TEXT,
  renewal_date DATE,
  ad_banner TEXT,
  membership_notes TEXT
);

CREATE TABLE IF NOT EXISTS competitions (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'liga',
  season TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  active_round INTEGER,
  starts_at DATE,
  ends_at DATE
);

CREATE TABLE IF NOT EXISTS league_identities (
  league_id TEXT PRIMARY KEY REFERENCES leagues(id) ON DELETE CASCADE,
  nickname TEXT,
  activities TEXT,
  public_intro TEXT,
  primary_color TEXT,
  accent_color TEXT,
  secondary_color TEXT
);

CREATE TABLE IF NOT EXISTS league_rules (
  league_id TEXT PRIMARY KEY REFERENCES leagues(id) ON DELETE CASCADE,
  withdrawal_policy TEXT NOT NULL DEFAULT 'award_walkover',
  forfeit_points INTEGER NOT NULL DEFAULT 3,
  forfeit_goals_for INTEGER NOT NULL DEFAULT 3,
  forfeit_goals_against INTEGER NOT NULL DEFAULT 0,
  yellow_suspension_limit INTEGER NOT NULL DEFAULT 3,
  default_red_suspension_matches INTEGER NOT NULL DEFAULT 1,
  discipline_scope TEXT NOT NULL DEFAULT 'competition',
  playoff_qualifiers INTEGER NOT NULL DEFAULT 8,
  minimum_playoff_appearances INTEGER NOT NULL DEFAULT 0,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS league_highlights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS league_announcements (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  date DATE
);

CREATE TABLE IF NOT EXISTS teams (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  coach TEXT,
  assistant_coach TEXT,
  address TEXT,
  colors TEXT,
  logo_url TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  withdrawn_round INTEGER,
  withdrawn_reason TEXT
);

CREATE TABLE IF NOT EXISTS players (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  number INTEGER,
  position TEXT,
  photo_url TEXT,
  photo_authorized BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS matches (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  stage TEXT NOT NULL DEFAULT 'regular',
  playoff_round TEXT,
  playoff_leg TEXT,
  aggregate_home INTEGER,
  aggregate_away INTEGER,
  round INTEGER NOT NULL,
  date DATE,
  time TEXT NOT NULL DEFAULT '',
  venue TEXT NOT NULL DEFAULT '',
  home_team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  away_team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'scheduled',
  workflow_status TEXT NOT NULL DEFAULT 'scheduled',
  capture_mode TEXT NOT NULL DEFAULT 'admin',
  current_report_id TEXT,
  published_at TIMESTAMPTZ,
  finalized_at TIMESTAMPTZ,
  home_goals INTEGER,
  away_goals INTEGER,
  observations TEXT,
  resolution_type TEXT NOT NULL DEFAULT 'normal',
  resolution_note TEXT,
  central_referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assistant_referee1_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  assistant_referee2_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  fourth_referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS match_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  local_uuid TEXT,
  type TEXT NOT NULL,
  player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  secondary_player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  assist_player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  team_id TEXT REFERENCES teams(id) ON DELETE SET NULL,
  event_team_side TEXT,
  subtype TEXT,
  period TEXT,
  minute INTEGER,
  minute_label TEXT,
  second INTEGER,
  suspension_matches INTEGER,
  suspension_indefinite BOOLEAN NOT NULL DEFAULT false,
  disciplinary_pending BOOLEAN NOT NULL DEFAULT false,
  reason TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_official BOOLEAN NOT NULL DEFAULT true,
  sync_status TEXT NOT NULL DEFAULT 'synced',
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS player_sanctions (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  matches INTEGER NOT NULL DEFAULT 0,
  indefinite BOOLEAN NOT NULL DEFAULT false,
  reason TEXT,
  date DATE,
  status TEXT NOT NULL DEFAULT 'active',
  notes TEXT
);

CREATE TABLE IF NOT EXISTS player_injuries (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  date DATE,
  expected_return DATE,
  needs_surgery BOOLEAN NOT NULL DEFAULT FALSE,
  needs_support BOOLEAN NOT NULL DEFAULT FALSE,
  support_detail TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  notes TEXT
);

CREATE TABLE IF NOT EXISTS team_affiliations (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  source_team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  target_team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active',
  starts_at DATE,
  ends_at DATE,
  player_numbers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS discipline_links (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  player_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS discipline_adjustments (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
  value INTEGER NOT NULL,
  date DATE,
  reason TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS discipline_resets (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
  date DATE,
  reason TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS player_appearance_adjustments (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
  value INTEGER NOT NULL,
  date DATE,
  reason TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
);

ALTER TABLE IF EXISTS teams
  ADD COLUMN IF NOT EXISTS competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS teams
  ADD COLUMN IF NOT EXISTS assistant_coach TEXT;

ALTER TABLE IF EXISTS teams
  ADD COLUMN IF NOT EXISTS address TEXT;

ALTER TABLE IF EXISTS teams
  ADD COLUMN IF NOT EXISTS logo_url TEXT;

ALTER TABLE IF EXISTS players
  ADD COLUMN IF NOT EXISTS competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS players
  ADD COLUMN IF NOT EXISTS photo_url TEXT;

ALTER TABLE IF EXISTS players
  ADD COLUMN IF NOT EXISTS photo_authorized BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS observations TEXT;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS central_referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS assistant_referee1_user_id TEXT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS assistant_referee2_user_id TEXT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS matches
  ADD COLUMN IF NOT EXISTS fourth_referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS league_rules
  ADD COLUMN IF NOT EXISTS discipline_scope TEXT NOT NULL DEFAULT 'competition';

ALTER TABLE IF EXISTS league_rules
  ADD COLUMN IF NOT EXISTS playoff_qualifiers INTEGER NOT NULL DEFAULT 8;

ALTER TABLE IF EXISTS league_rules
  ADD COLUMN IF NOT EXISTS minimum_playoff_appearances INTEGER NOT NULL DEFAULT 0;

UPDATE teams
SET competition_id = leagues.current_competition_id
FROM leagues
WHERE teams.league_id = leagues.id
  AND teams.competition_id IS NULL
  AND leagues.current_competition_id IS NOT NULL;

UPDATE players
SET competition_id = COALESCE(
  (SELECT teams.competition_id FROM teams WHERE teams.id = players.team_id),
  (SELECT leagues.current_competition_id FROM leagues WHERE leagues.id = players.league_id)
)
WHERE players.competition_id IS NULL
  AND COALESCE(
    (SELECT teams.competition_id FROM teams WHERE teams.id = players.team_id),
    (SELECT leagues.current_competition_id FROM leagues WHERE leagues.id = players.league_id)
  ) IS NOT NULL;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  league_id TEXT REFERENCES leagues(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  password_hash TEXT,
  failed_login_count INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  last_failed_login_at TIMESTAMPTZ
);

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS phone TEXT;

CREATE TABLE IF NOT EXISTS user_accesses (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  league_id TEXT REFERENCES leagues(id) ON DELETE CASCADE,
  team_id TEXT REFERENCES teams(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  permissions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_accesses_user ON user_accesses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_accesses_league_role ON user_accesses(league_id, role);

CREATE TABLE IF NOT EXISTS admin_activation_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  access_id TEXT REFERENCES user_accesses(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_activation_tokens_hash ON admin_activation_tokens(token_hash);

CREATE TABLE IF NOT EXISTS team_user_assignments (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'delegate',
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS team_roster_permissions (
  team_id TEXT PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  registration_enabled BOOLEAN NOT NULL DEFAULT false,
  enabled_until TIMESTAMPTZ,
  notes TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS team_delegate_activation_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assignment_id TEXT NOT NULL REFERENCES team_user_assignments(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referee_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  municipality TEXT NOT NULL,
  photo_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referee_activation_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referee_match_sheets (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  submitted_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  payload_json JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_review',
  review_note TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS match_rosters (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  submitted_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  captain_player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  goalkeeper_player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  captain_pin TEXT,
  players_json JSONB NOT NULL,
  starters_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  substitutes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  lineup_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'submitted',
  notes TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1,
  UNIQUE(match_id, team_id)
);

ALTER TABLE IF EXISTS match_rosters
  ADD COLUMN IF NOT EXISTS captain_pin TEXT;

CREATE TABLE IF NOT EXISTS match_team_pins (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  roster_id TEXT REFERENCES match_rosters(id) ON DELETE SET NULL,
  pin_hash TEXT NOT NULL,
  pin_salt TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  generated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revealed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  revealed_at TIMESTAMPTZ,
  invalidated_at TIMESTAMPTZ,
  used_at TIMESTAMPTZ,
  signed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(match_id, team_id)
);

CREATE TABLE IF NOT EXISTS match_sessions (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  capture_mode TEXT NOT NULL DEFAULT 'live',
  status TEXT NOT NULL DEFAULT 'draft',
  period TEXT,
  started_at TIMESTAMPTZ,
  paused_at TIMESTAMPTZ,
  saved_at TIMESTAMPTZ,
  resumed_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  suspended_at TIMESTAMPTZ,
  suspension_reason TEXT,
  clock_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS match_session_operations (
  operation_id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  session_id TEXT REFERENCES match_sessions(id) ON DELETE SET NULL,
  referee_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  operation_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'synced',
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS match_reports (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  session_id TEXT REFERENCES match_sessions(id) ON DELETE SET NULL,
  generated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  capture_mode TEXT NOT NULL DEFAULT 'admin',
  status TEXT NOT NULL DEFAULT 'draft',
  version INTEGER NOT NULL DEFAULT 1,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  home_goals INTEGER,
  away_goals INTEGER,
  generated_at TIMESTAMPTZ,
  finalized_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS match_report_signatures (
  id TEXT PRIMARY KEY,
  report_id TEXT NOT NULL REFERENCES match_reports(id) ON DELETE CASCADE,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  captain_player_id TEXT REFERENCES players(id) ON DELETE SET NULL,
  signed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  method TEXT NOT NULL DEFAULT 'pin',
  status TEXT NOT NULL DEFAULT 'signed',
  signed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip_address TEXT,
  user_agent TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(report_id, team_id)
);

CREATE TABLE IF NOT EXISTS match_report_disputes (
  id TEXT PRIMARY KEY,
  report_id TEXT NOT NULL REFERENCES match_reports(id) ON DELETE CASCADE,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  team_id TEXT REFERENCES teams(id) ON DELETE SET NULL,
  requested_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  resolution_note TEXT
);

CREATE TABLE IF NOT EXISTS match_sync_queue (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  session_id TEXT REFERENCES match_sessions(id) ON DELETE CASCADE,
  client_event_id TEXT,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS memberships (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  plan TEXT NOT NULL,
  status TEXT NOT NULL,
  renewal_date DATE
);

CREATE TABLE IF NOT EXISTS sponsors (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  placement TEXT NOT NULL DEFAULT 'home_banner',
  status TEXT NOT NULL DEFAULT 'active',
  image_url TEXT,
  link_url TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  notes TEXT
);

ALTER TABLE IF EXISTS sponsors
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS link_url TEXT,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  user_email TEXT,
  user_role TEXT,
  league_id TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS backup_records (
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  kind TEXT NOT NULL,
  status TEXT NOT NULL,
  file_name TEXT,
  file_path TEXT,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  checksum_sha256 TEXT,
  storage_bucket TEXT,
  storage_path TEXT,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  error_message TEXT
);

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_competitions_league ON competitions(league_id);
CREATE INDEX IF NOT EXISTS idx_teams_league ON teams(league_id);
CREATE INDEX IF NOT EXISTS idx_players_league_team ON players(league_id, team_id);
CREATE INDEX IF NOT EXISTS idx_matches_league_competition_round ON matches(league_id, competition_id, round);
CREATE INDEX IF NOT EXISTS idx_match_events_match ON match_events(match_id);
CREATE INDEX IF NOT EXISTS idx_player_sanctions_league ON player_sanctions(league_id, competition_id);
CREATE INDEX IF NOT EXISTS idx_player_injuries_league ON player_injuries(league_id, competition_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_league_created ON audit_logs(league_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backup_records_created ON backup_records(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_league ON users(league_id);
CREATE INDEX IF NOT EXISTS idx_users_lower_email ON users(lower(email));
CREATE INDEX IF NOT EXISTS idx_team_user_assignments_user ON team_user_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_team_user_assignments_league_team ON team_user_assignments(league_id, team_id);
CREATE INDEX IF NOT EXISTS idx_team_delegate_activation_tokens_hash ON team_delegate_activation_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_referee_activation_tokens_hash ON referee_activation_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_referee_profiles_municipality ON referee_profiles(municipality);
CREATE INDEX IF NOT EXISTS idx_referee_match_sheets_match ON referee_match_sheets(match_id);
CREATE INDEX IF NOT EXISTS idx_referee_match_sheets_status ON referee_match_sheets(status);
CREATE INDEX IF NOT EXISTS idx_match_rosters_match ON match_rosters(match_id);
CREATE INDEX IF NOT EXISTS idx_match_team_pins_match ON match_team_pins(match_id);
CREATE INDEX IF NOT EXISTS idx_match_sessions_match ON match_sessions(match_id);
CREATE INDEX IF NOT EXISTS idx_match_session_operations_match ON match_session_operations(match_id);
CREATE INDEX IF NOT EXISTS idx_match_reports_match ON match_reports(match_id);
CREATE INDEX IF NOT EXISTS idx_match_reports_status ON match_reports(status);
CREATE INDEX IF NOT EXISTS idx_match_report_signatures_report ON match_report_signatures(report_id);
CREATE INDEX IF NOT EXISTS idx_match_sync_queue_match_status ON match_sync_queue(match_id, status);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_user_expires ON password_reset_requests(user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_matches_referee_central ON matches(central_referee_user_id);
CREATE INDEX IF NOT EXISTS idx_matches_referee_assistant1 ON matches(assistant_referee1_user_id);
CREATE INDEX IF NOT EXISTS idx_matches_referee_assistant2 ON matches(assistant_referee2_user_id);
CREATE INDEX IF NOT EXISTS idx_matches_referee_fourth ON matches(fourth_referee_user_id);
